const translations = {
    home: 'Home',
    siteLab: 'SiteLab',
    elevateYourGastronomicBusiness: 'Elevate your gastronomic business with our web templates and custom applications. We transform ideas into cutting-edge digital experiences.',
    contact: 'Contact',
    writeUs: 'Write us!',
    our: 'OUR',
    team:'TEAM',
    ourTeamDescription: 'We take pride in bringing together a diverse group of brilliant minds, each contributing their unique experience to form an exceptional synergy.',
    experienceTitle: 'Experience',
    experienceContent: 'Each team member brings years of accumulated experience, consolidating a set of skills that spans from established technologies to the latest industry trends.',
    innovationTitle: 'Innovation',
    innovationContent: 'We are passionate about transforming cutting-edge ideas into digital realities, ensuring that each project reflects a fresh perspective and a vision for the future.',
    imaginationTitle: 'Imagination',
    imaginationContent: 'We excel at challenging conventional limits and embracing creativity in every aspect of our work.',
    pro: 'PRO',
    yects:'YECTS',
    projectsSubtitle: 'Welcome to Foodie\'s innovative portfolio. Discover how we elevate each project to new heights, merging client vision with our technical expertise to achieve extraordinary results.',
    project1Description: 'Responsive Views',
    project2Description: 'Specialized E-commerce',
    project3Description: 'Gastronomic Development',
    project4Description: 'Effective Minimalism',
    project5Description: 'Online Orders',
    project6Description: 'Personal Blogs',
    project7Description: 'Simplified Management',
    uiProjectCategory: 'AMAZING USER INTERFACES',
    adminPanelProjectCategory: 'CUSTOM ADMINISTRATION PANELS',
    contactCTA: 'Contact us to get an exclusive view of our innovative portfolio.',
    newsletterTitle: 'NEWSLETTER - DIGITAL ENTREPRENEURSHIP',
    newsletterSubtitle: 'Discover the essential keys to boost your brand in the digital age. By joining our newsletter, you will access valuable information that will unlock the potential of digital transformation for your business. Subscribe now to receive exclusive updates and strategic advice.',
    article1Title: 'Google Introduces New Search Algorithms for Enhanced User Experiences',
    article1Content: 'Google has announced significant updates to its search algorithms to prioritize user experience. Discover how these improvements will impact your website\'s ranking.',
    article2Title: 'Web Design Trends 2024: Innovation and Minimalism in Focus',
    article2Content: 'Explore the latest trends in web design for the coming year, from the incorporation of emerging technologies to the elegance of minimalism. Stay ahead with design strategies that will resonate with your audience.',
    article3Title: 'The Importance of Local SEO for Businesses: Strategies to Stand Out in Local Searches',
    article3Content: 'With the growing importance of local searches, this article explores effective SEO strategies for businesses looking to stand out in their geographical area. Learn how to optimize your online presence to attract local customers.',
    homeNavbar:"Home",
    ourTeamNavbar: "Our Team",
    proyectsNavbar: "Proyects",
    newsletterNavbar:"Newsletter",
    contactNavbar: "Contact",
    firstHaeding: "CONTACT US",
    secondHeading: "TO GET STARTED",
    namePlaceholder: "NAME",
    emailPlaceholder: "EMAIL",
    messagePlaceholder: "MESSAGE",
    nameError: {
      required: "This field is required.",
      maxLength: "Max length is 100 char.",
    },
    emailError: {
      required: "This field is required.",
      pattern: "Invalid email address.",
    },
    messageError: {
      required: "This field is required.",
      maxLength: "Max length is 2000 char.",
    },
    sendButton: "SEND",
  };
export default translations;