const translations = {
    home: 'Inicio',
    siteLab: 'SiteLab',
    elevateYourGastronomicBusiness: 'Eleva tu empresa gastronómica con nuestras plantillas web y aplicaciones personalizadas. Transformamos ideas en experiencias digitales de vanguardia.',
    contact: 'Contacto',
    writeUs: '¡Escríbenos!',
    our: 'NUESTRO',
    team: 'EQUIPO',
    ourTeamDescription: 'Nos enorgullece reunir un grupo diverso de mentes brillantes, cada una aportando su experiencia única para formar una sinergia excepcional.',
    experienceTitle: 'Experiencia',
    experienceContent: 'Cada miembro aporta años de experiencia acumulada, consolidando un conjunto de habilidades que abarca desde tecnologías establecidas hasta las últimas tendencias del sector.',
    innovationTitle: 'Innovación',
    innovationContent: 'Nos apasiona transformar ideas vanguardistas en realidades digitales, asegurando que cada proyecto refleje una perspectiva fresca y una visión hacia el futuro.',
    imaginationTitle: 'Imaginación',
    imaginationContent: 'Nos destacamos en desafiar los límites convencionales y abrazar la creatividad en cada aspecto de nuestro trabajo.',
    pro: 'PRO',
    yects:'YECTOS',
    projectsSubtitle: 'Bienvenido al portafolio innovador de Foodie. Descubre cómo elevamos cada proyecto a nuevas alturas, fusionando la visión del cliente con nuestra experiencia técnica para lograr resultados extraordinarios.',
    project1Description: 'Vistas Responsive',
    project2Description: 'E-commerce especializados',
    project3Description: 'Desarrollo Gastronómico',
    project4Description: 'Minimalismo Efectivo',
    project5Description: 'Pedidos en Línea',
    project6Description: 'Blogs Personales',
    project7Description: 'Gestión Simplificada',
    uiProjectCategory: 'INCREÍBLES INTERFACES DE USUARIO',
    adminPanelProjectCategory: 'PANELES DE ADMINISTRACIÓN PERSONALIZADOS',
    contactCTA: 'Contáctanos para acceder a una visión exclusiva de nuestro innovador portafolio.',
    newsletterTitle: 'NOTICIAS',
    newsletterSubtitle: 'Descubre las claves para impulsar tu marca en la era digital. Únete a nuestro boletín y desbloquea el potencial de la transformación digital para tu negocio.',
    article1Title: 'Google Introduce Nuevos Algoritmos de Búsqueda para Experiencias de Usuario Mejoradas',
    article1Content: 'Google ha anunciado actualizaciones significativas en sus algoritmos de búsqueda para priorizar la experiencia del usuario. Descubre cómo estas mejoras impactarán en el posicionamiento de tu sitio web.',
    article2Title: 'Tendencias de Diseño Web 2024: Innovación y Minimalismo en Foco',
    article2Content: 'Explora las últimas tendencias en diseño web para el próximo año, desde la incorporación de tecnologías emergentes hasta la elegancia del minimalismo. Mantente a la vanguardia con las estrategias de diseño que atraerán a tu audiencia.',
    article3Title: 'La Importancia del SEO Local para Empresas: Estrategias para Destacar en Búsquedas Locales',
    article3Content: 'Con la creciente importancia de las búsquedas locales, esta noticia explora estrategias efectivas de SEO para empresas que desean destacar en su área geográfica. Aprende cómo optimizar tu presencia en línea para atraer a clientes locales.',
    homeNavbar:"Inicio",
    ourTeamNavbar: "Nuestro Equipo",
    proyectsNavbar: "Proyectos",
    newsletterNavbar:"Noticias",
    contactNavbar: "Contacto",
    firstHaeding: "CONTÁCTANOS",
    secondHeading: "PARA EMPEZAR",
    namePlaceholder: "NOMBRE",
    emailPlaceholder: "CORREO ELECTRÓNICO",
    messagePlaceholder: "MENSAJE",
    nameError: {
      required: "Este campo es obligatorio.",
      maxLength: "Longitud máxima es de 100 caracteres.",
    },
    emailError: {
      required: "Este campo es obligatorio.",
      pattern: "Dirección de correo electrónico no válida.",
    },
    messageError: {
      required: "Este campo es obligatorio.",
      maxLength: "Longitud máxima es de 2000 caracteres.",
    },
    sendButton: "ENVIAR",
  };
export default translations;
  